set_property PACKAGE_PIN V10 [get_ports {in[3]}]
set_property PACKAGE_PIN U11 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[0]}]
set_property PACKAGE_PIN U12 [get_ports {in[1]}]
set_property PACKAGE_PIN H6 [get_ports {in[0]}]
set_property PACKAGE_PIN J15 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]

set_property PACKAGE_PIN V11 [get_ports {led[3]}]
set_property PACKAGE_PIN V12 [get_ports {led[2]}]
set_property PACKAGE_PIN V14 [get_ports {led[1]}]
set_property PACKAGE_PIN V15 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports out]
set_property PACKAGE_PIN V16 [get_ports out]

set_property PACKAGE_PIN L16 [get_ports {sel[0]}]
